name: hopegamings
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil:
  intl_phone_field: ^3.2.0
  google_fonts:
  pinput: ^2.3.0
  carousel_slider: ^4.2.1
  timer_count_down: ^2.2.2
  another_flushbar: ^1.12.30
  http: ^0.13.5
  sharedpreference: ^0.0.1
  page_transition: ^2.0.9
  confetti: ^0.7.0
  image_picker: ^0.8.7
  flutter_widget_from_html: ^0.9.0+2
  flutter_share: ^2.0.0
  dotted_border: ^2.0.0+3
  pretty_qr_code: ^2.0.3
  stop_watch_timer: ^3.0.1
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

